baseURL = "https://makrusali.github.io/"
languageCode = "en-us"
title = "Makrus Ali"
theme = "simple"
relativeURLs = true

[params]
    github = "https://makrusali.github.com"
    custom_css = ["css/main.css"]
    custom_js = ["js/main.js"]